import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Joystick } from "./Joystick";
import { playCue } from "./audio";
import { formatTime } from "./gameMath";
import { useGameSocket } from "./useGameSocket";
import type { GameSnapshot, InputVector, Profile, RuneDraft, Skin } from "./types";

const GameCanvas=lazy(()=>import("./GameCanvas").then(module=>({default:module.GameCanvas})));

const SKINS:{id:Skin;title:string;detail:string}[]=[{id:"sun",title:"Sun",detail:"straw hat · lantern"},{id:"tide",title:"Tide",detail:"conch hood · shell satchel"},{id:"storm",title:"Storm",detail:"feather cowl · short cape"},{id:"grove",title:"Grove",detail:"leaf hood · flower pouch"}];
const ZERO={x:0,y:0};
function newPlayerId(){return typeof crypto.randomUUID==="function"?crypto.randomUUID():`bog-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,12)}`}
function initialProfile():Profile{try{const saved=JSON.parse(localStorage.getItem("bogbound-profile-v1")??"") as Profile;if(saved.player_id&&saved.name&&saved.skin)return saved}catch{/* first visit */}return{player_id:newPlayerId(),name:`Traveler ${Math.floor(100+Math.random()*900)}`,skin:"sun"}}
function Lobby({snapshot,profile,onProfile,onStart,connected}:{snapshot:GameSnapshot;profile:Profile;onProfile:(p:Profile)=>void;onStart:()=>void;connected:boolean}){
  return <main className="lobby-shell"><section className="lobby-card"><div className="brand-mark">B</div><p className="eyebrow">FLOWER COMPUTER PRESENTS</p><h1>BOGBOUND</h1><p className="subtitle">A cooperative expedition into a living tropical bog.</p><div className="lobby-grid"><div><label className="field-label" htmlFor="player-name">YOUR NAME</label><input id="player-name" value={profile.name} maxLength={18} onChange={e=>onProfile({...profile,name:e.target.value})}/><p className="field-label skin-label">CHOOSE A TRAVELER <span>cosmetic only</span></p><div className="skin-grid">{SKINS.map(s=><button key={s.id} className={`skin-card skin-${s.id} ${profile.skin===s.id?"selected":""}`} onClick={()=>onProfile({...profile,skin:s.id})}><span className="skin-portrait"/><strong>{s.title}</strong><small>{s.detail}</small></button>)}</div><button className="primary start-button" disabled={!connected||snapshot.connected_players<1} onClick={onStart}>START EXPEDITION</button><p className="status-line"><i className={connected?"online":""}/>{connected?`${snapshot.connected_players} traveler${snapshot.connected_players===1?"":"s"} connected`:"Reconnecting…"}</p></div><aside className="join-panel"><img src="/qr.svg" alt="QR code for joining Bogbound"/><p>PLAY ON THIS NETWORK</p><code>{snapshot.join_url}</code><div className="how-to"><strong>HOW TO PLAY</strong><span>WASD / arrows or touch joystick</span><span>Attacks fire automatically</span><span>Collect motes · craft runes · revive friends</span></div></aside></div><div className="roster">{snapshot.players.map(p=><span key={p.id} className={`roster-pill skin-${p.skin}`}>{p.name}</span>)}</div></section></main>;
}

function Hud({snapshot,you,onBog,onMute,muted}:{snapshot:GameSnapshot;you:ReturnType<typeof findYou>;onBog:()=>void;onMute:()=>void;muted:boolean}){if(!you)return null;const boss=snapshot.enemies.find(enemy=>enemy.boss);const bossAngle=boss?Math.atan2(boss.pos.y-you.pos.y,boss.pos.x-you.pos.x)*180/Math.PI:0;return <><div className="hud top-left"><div className="hud-row"><strong>{you.name}</strong><span>LV {you.level}</span></div><div className="bar hp"><i style={{width:`${Math.max(0,you.hp/you.max_hp*100)}%`}}/></div><div className="hud-row tiny"><span>{Math.ceil(you.hp)} / {Math.ceil(you.max_hp)} HP</span><span>{you.element.toUpperCase()} {you.form.toUpperCase()}</span></div><div className="bar xp"><i style={{width:`${you.xp/you.xp_next*100}%`}}/></div></div><div className="hud top-center"><strong>{snapshot.wave_label}</strong><span>{formatTime(snapshot.remaining_ms)}</span>{snapshot.wave<5?<small className={`director-chip ${snapshot.director.mode.toLowerCase()}`}>FOLD DIRECTOR · {snapshot.director.mode.toUpperCase()} {snapshot.director.pressure}</small>:null}{snapshot.boss_hp?<div className="boss-bar"><i style={{width:`${snapshot.boss_hp[0]/snapshot.boss_hp[1]*100}%`}}/></div>:null}</div>{boss?<div className="boss-pointer"><span style={{transform:`rotate(${bossAngle}deg)`}}>➤</span><small>MOVE TO BOSS · AUTO-TARGET LOCKED</small></div>:null}<div className="hud-actions"><button onClick={onMute} aria-label={muted?"Enable sound":"Mute sound"}>{muted?"SOUND OFF":"SOUND ON"}</button><button onClick={onBog}>HOW BOG WORKS</button></div></>}
function findYou(snapshot:GameSnapshot){return snapshot.players.find(p=>p.id===snapshot.you)??null}

function RuneForge({rune,profile,send}:{rune:RuneDraft;profile:Profile;send:(m:Record<string,unknown>)=>void}){const [words,setWords]=useState("");useEffect(()=>setWords(""),[rune.id]);const compile=()=>{const incantation=words.trim();if(incantation)send({type:"compile_rune",player_id:profile.player_id,drop_id:rune.id,incantation})};const isCustom=words.trim()===rune.incantation;return <div className="modal-backdrop"><section className="draft rune-draft"><p className="eyebrow">{isCustom?"YOUR FORGED INCANTATION":"MYSTERIOUS WORD-RUNE · DEFAULT"}</p><blockquote className="incantation">“{rune.incantation}”</blockquote><small className="semantic-path">ESE EMBEDS ↓ ANNY MATCHES</small><h2>{rune.spell_name}</h2><div className="rune-pair"><span>{rune.element}</span><b>+</b><span>{rune.form}</span></div><p>{rune.description}</p><small>{Math.round(rune.confidence*100)}% semantic match · replaces your spell</small><div className="rune-forge"><label htmlFor="custom-incantation">OR WRITE YOUR OWN SPELL</label><div><input id="custom-incantation" value={words} maxLength={72} placeholder="e.g. burning birds hunt everything" onChange={event=>setWords(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")compile()}}/><button disabled={!words.trim()} onClick={compile}>FORGE</button></div></div><div className="draft-actions"><button className="primary" onClick={()=>send({type:"equip_rune",player_id:profile.player_id,drop_id:rune.id})}>EQUIP SHOWN SPELL</button><button onClick={()=>send({type:"salvage_rune",player_id:profile.player_id,drop_id:rune.id})}>SALVAGE +XP</button></div></section></div>}
function Drafts({snapshot,profile,send}:{snapshot:GameSnapshot;profile:Profile;send:(m:Record<string,unknown>)=>void}){if(snapshot.upgrade_draft){const draft=snapshot.upgrade_draft;return <div className="modal-backdrop"><section className="draft"><p className="eyebrow">LEVEL UP</p><h2>Choose a blessing</h2><div className="choice-grid">{draft.choices.map(choice=><button key={choice.id} onClick={()=>send({type:"choose_upgrade",player_id:profile.player_id,draft_id:draft.id,choice_id:choice.id})}><strong>{choice.title}</strong><span>{choice.description}</span></button>)}</div><small>The bog keeps moving. You are protected while choosing.</small></section></div>}if(snapshot.rune_draft)return <RuneForge rune={snapshot.rune_draft} profile={profile} send={send}/>;return null}

function BogPanel({snapshot,onClose}:{snapshot:GameSnapshot;onClose:()=>void}){return <aside className="bog-panel"><button className="close" onClick={onClose}>×</button><p className="eyebrow">LIVE BOGKIT VIEWS</p><h2>Incremental engine</h2><dl><div><dt>Fold commits</dt><dd>{snapshot.metrics.fold_commits}</dd></div><div><dt>Materialized players</dt><dd>{snapshot.metrics.materialized_players}</dd></div><div><dt>Materialized enemies</dt><dd>{snapshot.metrics.materialized_enemies}</dd></div><div><dt>ANNy HNSW queries</dt><dd>{snapshot.metrics.hnsw_queries}</dd></div><div><dt>ESE spell compiles</dt><dd>{snapshot.metrics.ese_compiles}</dd></div></dl><h3>FOLD ADAPTIVE DIRECTOR</h3><div className="director-card"><strong>{snapshot.director.mode} · {snapshot.director.pressure}/100</strong><span>{snapshot.director.reason}</span><small>Next spawn every {snapshot.director.spawn_interval_ms}ms</small></div><p>Fold incrementally maintains party health, downed travelers, total damage and enemies alive. The simulation consumes that materialized view to change spawn pace and enemy mix.</p><h3>ENEMIES BY TYPE</h3>{snapshot.metrics.enemy_counts.map(([kind,count])=><div className="metric-row" key={kind}><span>{kind}</span><b>{count}</b></div>)}</aside>}

function Results({snapshot,onRematch}:{snapshot:GameSnapshot;onRematch:()=>void}){const victory=snapshot.phase==="victory";const ranking=[...snapshot.players].sort((a,b)=>b.damage-a.damage);return <div className={`modal-backdrop result ${victory?"victory":"defeat"}`}><section><p className="eyebrow">EXPEDITION COMPLETE</p><h1>{victory?"THE BOG IS QUIET":"THE BOG ENDURES"}</h1><p>{victory?"The Fen Colossus has fallen.":"The Fen Colossus survived. Defeat it before time expires."}</p><div className="scoreboard">{ranking.map((p,i)=><div key={p.id}><b>#{i+1}</b><span>{p.name}</span><small>{p.damage} damage · {p.kills} kills · {p.revives} revives</small><em>{p.element} {p.form}</em></div>)}</div><button className="primary" onClick={onRematch}>RETURN TO SHORE</button></section></div>}

export default function App(){
  const [profile,setProfile]=useState<Profile>(initialProfile);const {snapshot,connected,send}=useGameSocket(profile);const [input,setInput]=useState<InputVector>(ZERO);const inputRef=useRef(input);const inputSequenceRef=useRef(0);const [showBog,setShowBog]=useState(false);const [muted,setMuted]=useState(()=>localStorage.getItem("bogbound-muted")==="true");const priorRef=useRef<{wave:number;phase:string;upgrade:boolean;rune:boolean}>({wave:0,phase:"lobby",upgrade:false,rune:false});
  useEffect(()=>{localStorage.setItem("bogbound-profile-v1",JSON.stringify(profile))},[profile]);
  useEffect(()=>{inputRef.current=input},[input]);
  useEffect(()=>{if(!snapshot||snapshot.phase!=="running"||!connected)return;let timer=0;const pressed=new Set<string>();const update=()=>{const x=(pressed.has("ArrowRight")||pressed.has("KeyD")?1:0)-(pressed.has("ArrowLeft")||pressed.has("KeyA")?1:0);const y=(pressed.has("ArrowDown")||pressed.has("KeyS")?1:0)-(pressed.has("ArrowUp")||pressed.has("KeyW")?1:0);setInput({x,y})};const releaseAll=()=>{pressed.clear();update()};const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","KeyW","KeyA","KeyS","KeyD"].includes(e.code)){e.preventDefault();pressed.add(e.code);update()}};const up=(e:KeyboardEvent)=>{pressed.delete(e.code);update()};const schedule=()=>{window.clearInterval(timer);if(!document.hidden&&navigator.onLine)timer=window.setInterval(()=>send({type:"input",player_id:profile.player_id,sequence:++inputSequenceRef.current,axis_x:inputRef.current.x,axis_y:inputRef.current.y}),50)};const visibility=()=>{if(document.hidden)releaseAll();schedule()};window.addEventListener("keydown",down);window.addEventListener("keyup",up);window.addEventListener("blur",releaseAll);window.addEventListener("online",schedule);window.addEventListener("offline",schedule);document.addEventListener("visibilitychange",visibility);schedule();return()=>{window.clearInterval(timer);window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);window.removeEventListener("blur",releaseAll);window.removeEventListener("online",schedule);window.removeEventListener("offline",schedule);document.removeEventListener("visibilitychange",visibility);setInput(ZERO)}},[snapshot?.phase,profile.player_id,send,connected]);
  useEffect(()=>{if(!snapshot||muted)return;const prior=priorRef.current;if(snapshot.wave>prior.wave&&prior.wave>0)playCue("wave");if(snapshot.upgrade_draft&&!prior.upgrade)playCue("level");if(snapshot.rune_draft&&!prior.rune)playCue("rune");if(snapshot.phase!==prior.phase&&snapshot.phase==="victory")playCue("victory");if(snapshot.phase!==prior.phase&&snapshot.phase==="defeat")playCue("defeat");priorRef.current={wave:snapshot.wave,phase:snapshot.phase,upgrade:Boolean(snapshot.upgrade_draft),rune:Boolean(snapshot.rune_draft)}},[snapshot,muted]);
  const updateProfile=useCallback((next:Profile)=>setProfile(next),[]);const joystick=useCallback((next:InputVector)=>setInput(next),[]);const you=useMemo(()=>snapshot?findYou(snapshot):null,[snapshot]);
  if(!snapshot)return <main className="loading"><div className="brand-mark">B</div><h1>BOGBOUND</h1><p>Finding the island…</p></main>;
  if(snapshot.phase==="lobby")return <Lobby snapshot={snapshot} profile={profile} onProfile={updateProfile} onStart={()=>send({type:"start_run"})} connected={connected}/>;
  return <main className="game-shell"><Suspense fallback={<div className="world-loading">Entering the bog…</div>}><GameCanvas snapshot={snapshot} input={input}/></Suspense><Hud snapshot={snapshot} you={you} onBog={()=>setShowBog(true)} muted={muted} onMute={()=>setMuted(value=>{localStorage.setItem("bogbound-muted",String(!value));return!value})}/><div className="announcement" key={snapshot.announcement}>{snapshot.announcement}</div>{you?.downed?<div className="downed-banner">DOWNED · CRAWL TOWARD A FRIEND</div>:null}<Joystick onChange={joystick}/><Drafts snapshot={snapshot} profile={profile} send={send}/>{showBog?<BogPanel snapshot={snapshot} onClose={()=>setShowBog(false)}/>:null}{!connected?<div className="connection-banner">Connection lost · the expedition is paused</div>:null}{snapshot.phase!=="running"?<Results snapshot={snapshot} onRematch={()=>send({type:"rematch"})}/>:null}</main>;
}
