import Phaser from "phaser";
import { createPixelArt } from "./pixelArt";
import type { GameSnapshot, InputVector } from "./types";

type SpriteMap = Map<string, Phaser.GameObjects.Sprite>;
export class BogboundScene extends Phaser.Scene {
  private snapshot:GameSnapshot|null=null;
  private movementInput:InputVector={x:0,y:0};
  private players:SpriteMap=new Map();private enemies:SpriteMap=new Map();private projectiles:SpriteMap=new Map();private pickups:SpriteMap=new Map();private telegraphs=new Map<string,Phaser.GameObjects.Arc>();
  private labels=new Map<string,Phaser.GameObjects.Text>();private followed:string|null=null;private lastAnnouncement:string|null=null;
  constructor(){super("bogbound")}
  create(){createPixelArt(this);this.cameras.main.setBackgroundColor("#2d7750");this.cameras.main.setBounds(0,0,1600,1600);this.applyViewportZoom();this.scale.on("resize",this.applyViewportZoom,this);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.scale.off("resize",this.applyViewportZoom,this));this.drawIsland();if(this.snapshot)this.syncEntities();}
  setSnapshot(snapshot:GameSnapshot){this.snapshot=snapshot;if(this.sys.isActive()){if(snapshot.announcement!==this.lastAnnouncement&&snapshot.announcement?.includes("COLOSSUS"))this.cameras.main.shake(120,.006);this.lastAnnouncement=snapshot.announcement;this.syncEntities()}}
  setInput(input:InputVector){this.movementInput=input}
  private applyViewportZoom(){const portrait=this.scale.width<600&&this.scale.height>this.scale.width;const landscapeZoom=Math.min(this.scale.width/480,this.scale.height/270);this.cameras.main.setZoom(portrait?2:Math.max(1,landscapeZoom));const resolution=this.labelResolution();for(const label of this.labels.values())label.setResolution(resolution)}
  private labelResolution(){return Math.max(2,Math.ceil(this.cameras.main.zoom))}
  private drawIsland(){
    const bg=this.add.tileSprite(800,800,1600,1600,"ground-0").setDepth(-20);bg.setTileScale(1);
    const random=new Phaser.Math.RandomDataGenerator(["bogbound-island"]);
    for(let i=0;i<7;i++){const x=random.between(140,1460),y=random.between(140,1460),w=random.between(90,180),h=random.between(55,105),key=i%3===0?"water":"sand";for(const[lx,ly,lw,lh]of[[x,y,w,h],[x-w*.48,y+8,w*.38,h*.6],[x+w*.48,y-6,w*.38,h*.68]])this.add.tileSprite(lx,ly,lw,lh,key).setDepth(-19).setAlpha(.92)}
    for(let i=0;i<110;i++){const x=random.between(40,1560),y=random.between(40,1560);const key=i%19===0?"ruin":i%13===0?"shell":i%11===0?"palm":i%5===0?"rock":"flower";this.add.image(x,y,key).setDepth(y-1).setAlpha(.9)}
    const border=this.add.graphics().setDepth(-10);border.lineStyle(22,0x1f6f72,1);border.strokeRect(10,10,1580,1580);border.lineStyle(4,0xe4c174,1);border.strokeRect(23,23,1554,1554);
  }
  private syncEntities(){const s=this.snapshot;if(!s)return;const seenPlayers=new Set<string>();for(const p of s.players){seenPlayers.add(p.id);let sprite=this.players.get(p.id);if(!sprite){sprite=this.add.sprite(p.pos.x,p.pos.y,`player-${p.skin}-down-0`).setDepth(p.pos.y);sprite.setData("tx",p.pos.x);sprite.setData("ty",p.pos.y);this.players.set(p.id,sprite);if(p.id!==s.you){const label=this.add.text(p.pos.x,p.pos.y-21,p.name,{fontFamily:"IBM Plex Mono",fontSize:"7px",color:"#fff4d0",backgroundColor:"#091511",padding:{x:2,y:1}}).setResolution(this.labelResolution()).setOrigin(.5).setDepth(3000);this.labels.set(p.id,label)}}sprite.setData("tx",p.pos.x);sprite.setData("ty",p.pos.y);sprite.setData("skin",p.skin);sprite.setData("downed",p.downed);sprite.setAlpha(p.downed ? .55 : 1);if(p.id===s.you&&this.followed!==p.id){this.cameras.main.startFollow(sprite,true,.14,.14);this.followed=p.id}}
    this.removeMissing(this.players,seenPlayers,id=>{this.labels.get(id)?.destroy();this.labels.delete(id)});
    const seenEnemies=new Set<string>();for(const e of s.enemies){const id=String(e.id);seenEnemies.add(id);let sprite=this.enemies.get(id);if(!sprite){sprite=this.add.sprite(e.pos.x,e.pos.y,`enemy-${e.kind}-0`);this.enemies.set(id,sprite)}sprite.setData("tx",e.pos.x);sprite.setData("ty",e.pos.y);sprite.setData("kind",e.kind);sprite.setData("hurt",e.hp/e.max_hp)}this.removeMissing(this.enemies,seenEnemies);
    const seenProjectiles=new Set<string>();for(const p of s.projectiles){const id=String(p.id);seenProjectiles.add(id);let sprite=this.projectiles.get(id);if(!sprite){sprite=this.add.sprite(p.pos.x,p.pos.y,p.hostile?"projectile-hostile":`projectile-${p.element}`);this.projectiles.set(id,sprite)}sprite.setData("tx",p.pos.x);sprite.setData("ty",p.pos.y)}this.removeMissing(this.projectiles,seenProjectiles);
    const seenPickups=new Set<string>();for(const p of s.pickups){const id=String(p.id);seenPickups.add(id);let sprite=this.pickups.get(id);if(!sprite){sprite=this.add.sprite(p.pos.x,p.pos.y,p.kind==="rune"?"pickup-rune":"pickup-xp");this.pickups.set(id,sprite)}sprite.setData("tx",p.pos.x);sprite.setData("ty",p.pos.y)}this.removeMissing(this.pickups,seenPickups);
    const seenTelegraphs=new Set<string>();for(const t of s.telegraphs){const id=String(t.id);seenTelegraphs.add(id);let ring=this.telegraphs.get(id);if(!ring){ring=this.add.circle(t.pos.x,t.pos.y,t.radius,0xe66a4d,.12).setStrokeStyle(3,0xffdc72,1);this.telegraphs.set(id,ring)}ring.setPosition(t.pos.x,t.pos.y).setRadius(t.radius).setAlpha(.55+Math.sin(t.remaining_ms/80)*.2).setDepth(t.pos.y-2)}for(const[id,ring]of this.telegraphs){if(!seenTelegraphs.has(id)){ring.destroy();this.telegraphs.delete(id)}}
  }
  private removeMissing(map:SpriteMap,seen:Set<string>,before?:(id:string)=>void){for(const[id,sprite]of map){if(!seen.has(id)){before?.(id);sprite.destroy();map.delete(id)}}}
  update(_time:number,deltaMs:number){if(!this.snapshot||this.snapshot.phase!=="running")return;const dt=Math.min(deltaMs/1000,.05);const frame=Math.floor(this.time.now/260)%2;for(const[id,sprite]of this.players){let tx=sprite.getData("tx") as number,ty=sprite.getData("ty") as number;if(id===this.snapshot.you){tx+=this.movementInput.x*145*dt;ty+=this.movementInput.y*145*dt}sprite.x=Phaser.Math.Linear(sprite.x,tx,.32);sprite.y=Phaser.Math.Linear(sprite.y,ty,.32);sprite.setDepth(sprite.y);const dx=tx-sprite.x,dy=ty-sprite.y;let direction="down";if(Math.abs(dx)>Math.abs(dy))direction=dx<0?"left":"right";else if(dy<0)direction="up";const skin=sprite.getData("skin") as string;sprite.setTexture(`player-${skin}-${direction}-${Math.abs(dx)+Math.abs(dy)>.1?frame:0}`);const label=this.labels.get(id);if(label){label.setPosition(sprite.x,sprite.y-21);label.setDepth(3000)}}for(const sprite of this.enemies.values()){sprite.x=Phaser.Math.Linear(sprite.x,sprite.getData("tx") as number,.28);sprite.y=Phaser.Math.Linear(sprite.y,sprite.getData("ty") as number,.28);sprite.setDepth(sprite.y);sprite.setTexture(`enemy-${sprite.getData("kind") as string}-${frame}`)}for(const map of [this.projectiles,this.pickups])for(const sprite of map.values()){sprite.x=Phaser.Math.Linear(sprite.x,sprite.getData("tx") as number,.5);sprite.y=Phaser.Math.Linear(sprite.y,sprite.getData("ty") as number,.5);sprite.setDepth(sprite.y);sprite.rotation+=dt*3}}
}
